language: ruby
rvm:
  - 2.2
install:
  - gem install bundler
  - bundle install
  - nvm install 6 && nvm use 6
  - npm install
  - node_modules/bower/bin/bower install
script:
  - npm run grunt build
after_success:
  - bash deploy.sh
