language: ruby
rvm:
  - 2.3
install:
  - gem install bundler
  - bundle install
  - nvm install 10 && nvm use 10
  - npm install
  - npx bower install
script:
  - npm run build
after_success:
  - bash deploy.sh
