

# Site settings
title: CSSclasses
email: contact@cssconf.eu
description: "CSSclasses is for beginners and experts alike: Using CSS as a simple and low-barrier entry language, we empower people to understand their browser and to learn how to experiment with code. Workshop and hackathon in one event."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cssclasses.cssconf.eu"
twitter_username: cssclasses
github_username:  cssconf

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty

include:
  - .nojekyll
exclude:
  - "bower.json"
  - "bower_components/"
  - "package.json"
  - "node_modules/"
  - "gruntfile.js"
  - "_sass/"
  - "README.md"

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Coaches
    url: /coaches/
  - title: Attendees
    url: /attendees/
  - title: Learning Materials
    url: /materials/
  - title: Code of Conduct
    url: /code-of-conduct/
