

# Site settings
title: CSSclasses
email: contact@cssconf.eu
description: "CSSclasses is for beginners and experts alike: Using CSS as a simple and low-barrier entry language, we empower people to understand their browser and to learn how to experiment with code. Workshop and hackathon in one event."
baseurl: ""
url: "https://cssclass.es"
twitter_username: CSSclasses
github_username:  CSSclasses

# Build settings
markdown: kramdown
permalink: /:categories/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - .nojekyll
  - "js/cssclasses.min.js"
  - "js/cssclasses.min.js.map"

exclude:
  - "_sass/"
  - "bower.json"
  - "bower_components/"
  - "Gemfile"
  - "Gemfile.lock"
  - "gruntfile.js"
  - "node_modules/"
  - "package.json"
  - "README.md"

navigation:
  - title: Home
    url: /
  - title: Materials
    url: /materials/
  - title: About
    url: /about/
  - title: Coaches
    url: /coaches/
  - title: Attendees
    url: /attendees/
  - title: Run Your Own Event
    url: /run-your-own-event/
  - title: Code of Conduct
    url: /code-of-conduct/
